### PR TITLE
Fixed #76

### LINKED ISSUE #76: Convert uses excessive memory while producing TIA report
Converting 700MB class files with 25GB RAM
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.HashMap.resize(HashMap.java:704)
        at java.util.HashMap.putVal(HashMap.java:663)
        at java.util.HashMap.put(HashMap.java:612)
        at java.util.HashSet.add(HashSet.java:220)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
        at shadow.com.teamscale.report.testwise.model.builder.FileCoverageBuilder.addLines(FileCoverageBuilder.java:53)
        at shadow.com.teamscale.report.testwise.jacoco.cache.ClassCoverageLookup.fillFileCoverage(ClassCoverageLookup.java:120)
        at shadow.com.teamscale.report.testwise.jacoco.cache.ClassCoverageLookup.getFileCoverage(ClassCoverageLookup.java:94)
        at shadow.com.teamscale.report.testwise.jacoco.cache.ProbesCache.getCoverage(ProbesCache.java:84)
        at shadow.com.teamscale.report.testwise.jacoco.CachingExecutionDataReader.buildCoverage(CachingExecutionDataReader.java:92)
        at shadow.com.teamscale.report.testwise.jacoco.CachingExecutionDataReader.buildCoverage(CachingExecutionDataReader.java:77)
        at shadow.com.teamscale.report.testwise.jacoco.JaCoCoTestwiseReportGenerator.convert(JaCoCoTestwiseReportGenerator.java:53)
        at com.teamscale.jacoco.agent.convert.Converter.runTestwiseCoverageReportGeneration(Converter.java:92)
        at com.teamscale.jacoco.agent.convert.ConvertCommand.run(ConvertCommand.java:161)
        at com.teamscale.jacoco.agent.Main.parseCommandLineAndRun(Main.java:67)
        at com.teamscale.jacoco.agent.Main.main(Main.java:38)
```

### PR DESCRIPTION
**Pull request by DreierF**
- [x] [No new Teamscale findings](https://build.cqse.eu/teamscale/delta.html#input/jacoco-client/?showMergeFindings=true)
- [x] [Changes are tested adequately](https://build.cqse.eu/teamscale/tests.html#/jacoco-client/)
- [x] README.md updated in case of user-visible changes
- [x] CHANGELOG.md updated

### CODE REVIEW

File: report-generator/src/main/java/com/teamscale/report/testwise/jacoco/CachingExecutionDataReader.java [hunk 1]
```diff
@@ -63,35 +63,57 @@ public void analyzeClassDirs(Collection<File> classesDirectories, Predicate<Stri
...
 	 */
-	public TestwiseCoverage buildCoverage(List<Dump> dumps, Predicate<String> locationIncludeFilter) {
-		TestwiseCoverage testwiseCoverage = new TestwiseCoverage();
-		for (Dump dump : dumps) {
+	public DumpConsumer buildCoverageConsumer(Predicate<String> locationIncludeFilter,
+											  Consumer<TestCoverageBuilder> nextConsumer) {
+		return new DumpConsumer(logger, locationIncludeFilter, nextConsumer);
+	}
+
+	public class DumpConsumer implements Consumer<Dump> {
```
Comment (albertsteckermeier) [inline report-generator/src/main/java/com/teamscale/report/testwise/jacoco/CachingExecutionDataReader.java]: Missing comment.
